# Finalize dataset for tutorial

## Standard Imports

In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#from IPython import display
from IPython.display import display, HTML
%matplotlib inline
import time
pd.set_option('display.max_columns', None) # to see all columns of df.head()
np.random.seed(31415) # set the random seed

In [2]:
path="/Users/rousseau/Downloads"

outputdatapath="/Users/rousseau/Google\ Drive/GD_openData/dataWW_ATLAS_openData13TeV_filtered/"

!ls -lrt {outputdatapath}
outputdatapath=os.path.abspath(outputdatapath).replace("\ ", " ")  # try to normalise the path (annoyance with the space)
print ("Will write data file to : ",outputdatapath)

total 91424
-rw-r--r--+ 1 rousseau  staff    498849 13 mai 17:01 dataWW_d1_3K.csv
-rw-r--r--+ 1 rousseau  staff   9059494 13 mai 20:33 dataWW_d1_150k.csv.gz
-rw-r--r--+ 1 rousseau  staff  35812815 13 mai 22:24 dataWW_d1_600k.csv.gz
Will write data file to :  /Users/rousseau/Google Drive/GD_openData/dataWW_ATLAS_openData13TeV_filtered

In [3]:


# cross section to come from https://github.com/atlas-outreach-data-tools/atlas-outreach-cpp-framework-13tev/blob/master/Plotting/inputfiles/Files_HWW.txt
# the one in the input file can be wrong
labels=["qq","ggH","VBFH"]
detaillevel="d1"
cross_sections={"qq":12.466,"ggH":0.58,"VBFH":0.04} # in fb

outputfilename=os.path.join(outputdatapath,"dataWW_"+detaillevel+".csv.gz")

# total integrated luminosity ATLAS 2012 : 139fb^-1
luminosity=10 #fb^-1 about 2015 data 



import os

all_events={}
for label in labels:        
    filepath=os.path.join(path,"dataWW_"+label+"_"+detaillevel+".csv.gz")
    all_events[label] = pd.read_csv(filepath) 


#qq_events = pd.read_csv("/Users/rousseau/Google Drive/GD_opendata/dataWW_ATLAS_openData13TeV_filtered/dataWW_qq_d0_1000k.csv.gz",sep="," ) 
#ggh_events = pd.read_csv(datapath+"dataWW_ggH_d0_100k.csv.gz",sep=",") 
#vbfh_events = pd.read_hdf(datapath+"dataWW_VBFH.hdf","VBFH",WRITEABLE=False ) #Vector Boson Fusion http://opendata.cern.ch/record/3826
all_events["VBFH"].columns
display(all_events["VBFH"].head())
display(all_events["VBFH"].describe())

,eventNumber,channelNumber,met_et,met_phi,lep_n,lep_pt_0,lep_pt_1,lep_eta_0,lep_eta_1,lep_phi_0,lep_phi_1,lep_E_0,lep_E_1,lep_charge_0,lep_charge_1,lep_type_0,lep_type_1,jet_n,jet_pt_0,jet_pt_1,jet_eta_0,jet_eta_1,jet_phi_0,jet_phi_1,jet_E_0,jet_E_1,mcWeight,runNumber,XSection,SumWeights
0,384,345323,116.8600,-1.26540,2,57.987,33.692,-0.17389,-0.875490,-1.489800,-1.62820,58866.0,47451.0,-1,1,13,11,2,29.895,29.083,-2.4547,1.21450,-2.4571,0.57501,175420.0,53507.0,3.7499,284500,1.9059,4390000.0
1,841,345323,112.0200,-0.86899,2,29.739,12.656,-1.02240,0.053344,0.935910,0.62834,46684.0,12675.0,1,-1,11,13,3,99.283,32.058,-2.3502,0.76057,3.1212,-1.51410,525480.0,42347.0,3.7499,284500,1.9059,4390000.0
2,184,345323,314.2400,-0.37074,2,42.921,18.685,-0.89607,-1.140800,-0.552370,-1.64300,61337.0,32220.0,1,-1,13,11,3,243.040,73.488,1.2938,-2.06750,2.7464,-2.92700,476640.0,295290.0,3.7499,284500,1.9059,4390000.0
3,817,345323,72.0230,-0.99177,2,67.623,65.901,0.90236,0.625700,-0.045364,-0.46053,97073.0,79228.0,-1,1,13,13,2,213.950,23.831,2.4991,2.47340,2.9268,0.57894,1311000.0,142500.0,3.7499,284500,1.9059,4390000.0
4,1588,345323,4.4252,-2.43290,2,40.543,21.005,0.44649,0.291370,1.649700,-0.47812,44652.0,21903.0,1,-1,11,13,0,-7.000,-7.000,-7.0000,-7.00000,-7.0000,-7.00000,-7.0,-7.0,3.7499,284500,1.9059,4390000.0

,eventNumber,channelNumber,met_et,met_phi,lep_n,lep_pt_0,lep_pt_1,lep_eta_0,lep_eta_1,lep_phi_0,lep_phi_1,lep_E_0,lep_E_1,lep_charge_0,lep_charge_1,lep_type_0,lep_type_1,jet_n,jet_pt_0,jet_pt_1,jet_eta_0,jet_eta_1,jet_phi_0,jet_phi_1,jet_E_0,jet_E_1,mcWeight,runNumber,XSection,SumWeights
count,2.000000e+05,200000.0,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,2.000000e+05,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,2.000000e+05,2.000000e+05,200000.000000,200000.0,2.000000e+05,200000.0
mean,5.618368e+05,345323.0,61.254961,-0.006217,2.006050,57.741068,25.521284,0.002152,0.002656,0.002530,0.009040,1.056596e+05,48120.910842,-0.002700,0.003400,11.908710,11.961920,1.326380,70.880788,12.022779,-1.434421,-4.479583,-1.445405,-4.479064,1.875346e+05,4.543356e+04,3.737188,284500.0,1.905900e+00,4390000.0
std,3.208474e+05,0.0,45.104270,1.812738,0.077996,33.593566,15.738560,1.158605,1.187890,1.810775,1.814271,8.409278e+04,42408.649736,0.999999,0.999997,0.995827,0.999277,1.058495,72.620442,31.605595,3.145023,3.491334,3.256724,3.533596,2.277730e+05,9.405599e+04,0.308509,0.0,7.714071e-12,0.0
min,2.000000e+00,345323.0,0.095622,-3.141600,2.000000,25.001000,7.000300,-2.696400,-2.699900,-3.141500,-3.141500,2.502300e+04,7003.800000,-1.000000,-1.000000,11.000000,11.000000,0.000000,-7.000000,-7.000000,-7.000000,-7.000000,-7.000000,-7.000000,-7.000000e+00,-7.000000e+00,-3.749900,284500.0,1.905900e+00,4390000.0
25%,3.277008e+05,345323.0,33.251750,-1.576500,2.000000,37.055000,14.428000,-0.848492,-0.892413,-1.567525,-1.563100,5.235075e+04,21771.750000,-1.000000,-1.000000,11.000000,11.000000,1.000000,24.793750,-7.000000,-2.275500,-7.000000,-2.790425,-7.000000,4.011950e+04,-7.000000e+00,3.749900,284500.0,1.905900e+00,4390000.0
50%,5.014455e+05,345323.0,51.911500,-0.018328,2.000000,49.256000,22.260000,0.004078,0.006082,0.014238,0.017809,7.927600e+04,35129.000000,-1.000000,1.000000,11.000000,11.000000,1.000000,57.474000,-7.000000,-0.771710,-7.000000,-0.828880,-7.000000,1.193700e+05,-7.000000e+00,3.749900,284500.0,1.905900e+00,4390000.0
75%,7.697402e+05,345323.0,76.906000,1.560400,2.000000,68.387000,31.862000,0.855852,0.897752,1.570525,1.577100,1.295025e+05,58667.000000,1.000000,1.000000,13.000000,13.000000,2.000000,101.700000,26.742000,1.089900,-1.168700,1.157900,-1.226900,2.514300e+05,5.723350e+04,3.749900,284500.0,1.905900e+00,4390000.0
max,1.199997e+06,345323.0,3634.600000,3.141600,4.000000,3624.600000,382.170000,2.699800,2.699200,3.141500,3.141500,3.624700e+06,870750.000000,1.000000,1.000000,13.000000,13.000000,10.000000,1658.200000,586.590000,2.500000,2.499900,3.141600,3.141600,4.006900e+06,2.388900e+06,3.749900,284500.0,1.905900e+00,4390000.0

In [4]:
# compute normalisation factors
for label in labels:
    sumw=all_events[label]["mcWeight"].sum()
    totalw=all_events[label]["SumWeights"][0]
    weight_correction=1/sumw
    print("For file ",label," n events ", all_events[label].shape[0]," sum of weights:",sumw, " expected:",totalw," weight correction",weight_correction)
    scaling=luminosity*cross_sections[label]*weight_correction
    print (" now multiply all weights by ",scaling)
    all_events[label]["mcWeight"]*=scaling

For file  qq  n events  200000  sum of weights: 63409.528374299996  expected: 5039300.0  weight correction 1.577050051684822e-05
 now multiply all weights by  0.001965950594430299
For file  ggH  n events  200000  sum of weights: 5673385.703999999  expected: 55833000.0  weight correction 1.762615926667834e-07
 now multiply all weights by  1.0223172374673438e-06
For file  VBFH  n events  200000  sum of weights: 747437.5677999997  expected: 4390000.0  weight correction 1.3379043857046015e-06
 now multiply all weights by  5.351617542818406e-07

In [5]:
# add new label for each dataset
all_events["qq"]["label"] = 0 # qq background
all_events["ggH"]["label"] = 1 # ggH signal
all_events["VBFH"]["label"] = 1 # VBFH signal

In [6]:
# merge the dataset
fulldata = pd.concat([all_events["qq"],all_events["ggH"],all_events["VBFH"]]) # merge all dataset
# randomise
fulldata=fulldata.sample(frac=1).reset_index(drop=True) 
display(fulldata.describe())
display(fulldata.columns)

,eventNumber,channelNumber,met_et,met_phi,lep_n,lep_pt_0,lep_pt_1,lep_eta_0,lep_eta_1,lep_phi_0,lep_phi_1,lep_E_0,lep_E_1,lep_charge_0,lep_charge_1,lep_type_0,lep_type_1,jet_n,jet_pt_0,jet_pt_1,jet_eta_0,jet_eta_1,jet_phi_0,jet_phi_1,jet_E_0,jet_E_1,mcWeight,runNumber,XSection,SumWeights,label
count,6.000000e+05,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000,6.000000e+05,6.000000e+05,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000,600000.000000,6.000000e+05,6.000000e+05,600000.000000,600000.0,600000.000000,6.000000e+05,600000.000000
mean,7.029775e+05,351379.666667,60.365356,-0.008556,2.005748,60.270328,28.133970,0.000269,-0.000664,0.005219,0.008524,1.164008e+05,5.630948e+04,-0.027027,0.027037,11.907273,11.958010,1.334185,59.606114,13.521164,-1.934521,-4.402337,-1.939645,-4.401941,1.375410e+05,4.125468e+04,0.000218,284500.0,9.448300,2.175410e+07,0.666667
std,4.568961e+05,8564.720183,48.153210,1.812778,0.076061,42.676858,20.352272,1.210614,1.235890,1.811177,1.814205,1.083341e+05,5.748834e+04,0.999636,0.999635,0.995692,0.999119,1.232632,79.586143,38.074439,3.349404,3.491304,3.489197,3.559421,1.980717e+05,8.990068e+04,0.000736,0.0,5.368655,2.409890e+07,0.471405
min,1.000000e+00,345323.000000,0.044211,-3.141600,2.000000,25.000000,7.000300,-2.700000,-2.699900,-3.141600,-3.141600,2.501300e+04,7.003800e+03,-1.000000,-1.000000,11.000000,11.000000,0.000000,-7.000000,-7.000000,-7.000000,-7.000000,-7.000000,-7.000000,-7.000000e+00,-7.000000e+00,-0.045557,284500.0,1.905900,4.390000e+06,0.000000
25%,3.498568e+05,345323.000000,33.196000,-1.577600,2.000000,36.624750,15.316000,-0.899650,-0.946043,-1.560200,-1.562900,5.221675e+04,2.329100e+04,-1.000000,-1.000000,11.000000,11.000000,0.000000,-7.000000,-7.000000,-7.000000,-7.000000,-7.000000,-7.000000,-7.000000e+00,-7.000000e+00,0.000002,284500.0,1.905900,4.390000e+06,0.000000
50%,6.678815e+05,345324.000000,50.082000,-0.018694,2.000000,48.229500,23.644000,0.003413,0.002974,0.014583,0.018823,8.184450e+04,3.824900e+04,-1.000000,1.000000,11.000000,11.000000,1.000000,38.744000,-7.000000,-0.891010,-7.000000,-1.210600,-7.000000,7.501700e+04,-7.000000e+00,0.000029,284500.0,12.466000,5.039300e+06,1.000000
75%,1.001273e+06,363492.000000,73.032250,1.559300,2.000000,68.979000,34.149000,0.901950,0.942210,1.573000,1.577300,1.412400e+05,6.730825e+04,1.000000,1.000000,13.000000,13.000000,2.000000,84.291250,26.881000,0.724705,-0.821005,0.967753,-1.088575,1.766200e+05,5.060500e+04,0.000197,284500.0,13.973000,5.583300e+07,1.000000
max,1.997995e+06,363492.000000,7062.200000,3.141600,5.000000,7041.400000,744.900000,2.699800,2.700000,3.141500,3.141600,7.041600e+06,2.107900e+06,1.000000,1.000000,13.000000,13.000000,13.000000,1658.200000,1429.800000,2.500000,2.500000,3.141600,3.141600,5.638800e+06,2.784300e+06,0.052420,284500.0,13.973000,5.583300e+07,1.000000

Index(['eventNumber', 'channelNumber', 'met_et', 'met_phi', 'lep_n',
       'lep_pt_0', 'lep_pt_1', 'lep_eta_0', 'lep_eta_1', 'lep_phi_0',
       'lep_phi_1', 'lep_E_0', 'lep_E_1', 'lep_charge_0', 'lep_charge_1',
       'lep_type_0', 'lep_type_1', 'jet_n', 'jet_pt_0', 'jet_pt_1',
       'jet_eta_0', 'jet_eta_1', 'jet_phi_0', 'jet_phi_1', 'jet_E_0',
       'jet_E_1', 'mcWeight', 'runNumber', 'XSection', 'SumWeights', 'label'],
      dtype='object')

In [7]:
#dop some columns
fulldata.drop(columns=["XSection","SumWeights"],inplace=True)

#reorder some columns
varlist=fulldata.columns.tolist()
oldvarlist=varlist.copy()

#some stuff to the end
for aname in ["channelNumber"]:
    if not aname in varlist:
        continue
    varlist.remove(aname)
    varlist.append(aname)
    
#some stuff at the beginning
varlist.remove("label")
varlist.insert(1,"label")    

# check we have only reordered
if sorted(oldvarlist)!=sorted(varlist):
    print ("before:",sorted(oldvarlist) )
    print ("after :",sorted(varlist) )
    raise Exception("something wrong when reordering the columns!")

# do the reordering
fulldata = fulldata.reindex(columns=varlist)
display(fulldata.head())

,eventNumber,label,met_et,met_phi,lep_n,lep_pt_0,lep_pt_1,lep_eta_0,lep_eta_1,lep_phi_0,lep_phi_1,lep_E_0,lep_E_1,lep_charge_0,lep_charge_1,lep_type_0,lep_type_1,jet_n,jet_pt_0,jet_pt_1,jet_eta_0,jet_eta_1,jet_phi_0,jet_phi_1,jet_E_0,jet_E_1,mcWeight,runNumber,channelNumber
0,249632,1,25.118,1.14010,2,46.439,44.589,0.131030,0.40654,2.34760,-2.41510,46838.0,48325.0,1,-1,13,11,1,53.680,-7.000,2.4346,-7.00000,-0.76667,-7.00000,308720.0,-7.0,0.000002,284500,345323
1,892975,1,27.974,0.84442,2,86.819,55.438,-0.017265,-0.16338,-1.44520,-1.72950,86832.0,56179.0,1,-1,11,13,1,126.700,-7.000,-1.2789,-7.00000,1.66290,-7.00000,245670.0,-7.0,0.000002,284500,345323
2,730573,0,123.290,-2.94810,2,105.810,40.506,-1.338900,-1.03500,0.68539,-0.90527,215700.0,64211.0,1,-1,13,13,0,-7.000,-7.000,-7.0000,-7.00000,-7.00000,-7.00000,-7.0,-7.0,0.002468,284500,363492
3,717584,0,78.558,1.04450,2,56.666,35.124,2.294600,1.88700,2.13110,-2.83820,283930.0,118570.0,-1,1,11,11,2,79.799,53.942,1.6270,0.55314,-1.84880,-0.47055,211610.0,63629.0,0.000197,284500,363492
4,319020,0,15.863,0.74840,2,94.708,72.811,0.812740,0.77954,1.84940,0.45967,127750.0,96077.0,-1,1,11,11,1,143.180,-7.000,-0.6358,-7.00000,-1.91230,-7.00000,173810.0,-7.0,0.000197,284500,363492

In [8]:
#write final dataset 
fulldata.to_csv(outputfilename,float_format='%.5g',index = False)# do csv file